apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
  labels:
    app: server-autoscaling
spec:
  replicas: 1
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
        app: server-autoscaling
    spec:
      containers:
        - name: server
          image: myserver
          imagePullPolicy: Never
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000