apiVersion: v1
kind: Service
metadata:
  name: server-node-port-service
  labels:
    app: server-autoscaling
spec:
  type: NodePort
  selector:
    component: server
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30000
