apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: server-horizontal-pod-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: server-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 15
